name: Build IPA for TrollStore

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build .app (Skip signing, no Pod)
        run: |
          xcodebuild \
            -project XXTExplorer.xcodeproj \
            -scheme XXTouch \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -derivedDataPath build

      - name: Package .ipa
        run: |
          cd build/Build/Products/Release-iphoneos
          mkdir Payload
          mv XXTExplorer.app Payload/
          zip -r XXTExplorer.ipa Payload
          mv XXTExplorer.ipa $GITHUB_WORKSPACE/

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: XXTExplorer-TrollStore
          path: XXTExplorer.ipa
